# This file will be included by the Makefile under the project directory.

FLOAT_OBJ := $(FLOAT:.a=.o)

$(FLOAT): $(FLOAT_OBJ)
	ar r $(FLOAT) $(FLOAT_OBJ)

# TODO: write a rule for generating $(FLOAT_OBJ)

#VPATH = lib-common

$(FLOAT_OBJ): FLOAT.c FLOAT.h
#	mkdir -p obj/lib-common
	gcc -m32 -fno-builtin FLOAT.c
#	mkdir -p obj/lib-common
