# This file will be included by the Makefile under the project directory.

FLOAT_OBJ := $(FLOAT:.a=.o)

$(FLOAT): $(FLOAT_OBJ)
	ar r $(FLOAT) $(FLOAT_OBJ)

# TODO: write a rule for generating $(FLOAT_OBJ)

MYPATH = ./lib-common
MYSRC = $(MYPATH)/FLOAT.c
MYOBJ = ./obj/lib-common/FLOAT.o
MYCFLAGS = -m32 -fno-builtin

$(FLOAT_OBJ): $(MYSRC)
	mkdir -p obj/lib-common
	gcc -I$(MYPATH) $(MYCFLAGS) -c $(MYSRC) -o $(MYOBJ)
#	mkdir -p obj/lib-common
